export const demoEvents = [
    {
        id: 'wedding',
        name: 'Olivia & Alexander',
        type: 'Wedding',
        date: '24 October 2026',
        place: 'The Orangery, Cotswolds',
        guests: 120,
        budget: 25000,
        image: '/images/preview-garden.jpg',
        imageAlt: 'A wedding couple holding an autumn bouquet',
        initial: 'OA',
        people: ['Olivia', 'Alexander', 'Emma'],
        tasks: [
            {
                id: 1,
                title: 'Confirm the seasonal menu',
                category: 'Catering',
                due: 'Today',
                done: false,
                owner: 'Olivia',
            },
            {
                id: 2,
                title: 'Review the floral proposal',
                category: 'Design',
                due: 'Tomorrow',
                done: false,
                owner: 'Emma',
            },
            {
                id: 3,
                title: 'Send the final invitations',
                category: 'Guests',
                due: '21 Sep',
                done: true,
                owner: 'Alexander',
            },
            {
                id: 4,
                title: 'Book the evening musicians',
                category: 'Experience',
                due: '23 Sep',
                done: false,
                owner: 'Olivia',
            },
            {
                id: 5,
                title: 'Confirm the venue',
                category: 'Venue',
                due: '18 Sep',
                done: true,
                owner: 'Emma',
            },
        ],
        vendors: [
            {
                id: 1,
                name: 'The Orangery',
                category: 'Venue',
                price: 8500,
                status: 'Booked',
                detail: 'Exclusive use · 120 guests',
                initial: 'O',
            },
            {
                id: 2,
                name: 'Gather & Graze',
                category: 'Catering',
                price: 4200,
                status: 'Shortlisted',
                detail: 'Seasonal three-course menu',
                initial: 'G',
            },
            {
                id: 3,
                name: 'The Supper Club',
                category: 'Catering',
                price: 4800,
                status: 'Considering',
                detail: 'Family-style sharing menu',
                initial: 'S',
            },
            {
                id: 4,
                name: 'Stem & Story',
                category: 'Florals',
                price: 1800,
                status: 'Shortlisted',
                detail: 'Ceremony & table arrangements',
                initial: 'S',
            },
        ],
        expenses: [
            { name: 'Venue & hire', amount: 8500, paid: 4250, due: '01 Oct' },
            { name: 'Food & drink', amount: 4200, paid: 1000, due: '10 Oct' },
            { name: 'Florals & styling', amount: 1800, paid: 0, due: '12 Oct' },
            {
                name: 'Music & photography',
                amount: 3950,
                paid: 1500,
                due: '17 Oct',
            },
        ],
    },
    {
        id: 'corporate',
        name: 'The Autumn Assembly',
        type: 'Company retreat',
        date: '30 October 2026',
        place: 'Heckfield Place, Hampshire',
        guests: 64,
        budget: 32000,
        image: '/images/preview-estate.jpg',
        imageAlt: 'An event hall with chandeliers and arranged tables',
        initial: 'AA',
        people: ['Emma', 'James', 'Alex'],
        tasks: [
            {
                id: 1,
                title: 'Confirm the retreat menu',
                category: 'Catering',
                due: 'Today',
                done: false,
                owner: 'Emma',
            },
            {
                id: 2,
                title: 'Review the stage design',
                category: 'Design',
                due: 'Tomorrow',
                done: false,
                owner: 'James',
            },
            {
                id: 3,
                title: 'Send the team invitations',
                category: 'Guests',
                due: '21 Sep',
                done: true,
                owner: 'Alex',
            },
            {
                id: 4,
                title: 'Confirm the keynote speaker',
                category: 'Experience',
                due: '23 Sep',
                done: false,
                owner: 'Emma',
            },
            {
                id: 5,
                title: 'Book the meeting rooms',
                category: 'Venue',
                due: '18 Sep',
                done: true,
                owner: 'James',
            },
        ],
        vendors: [
            {
                id: 1,
                name: 'Heckfield Place',
                category: 'Venue',
                price: 12000,
                status: 'Booked',
                detail: 'Meeting spaces & overnight stays',
                initial: 'H',
            },
            {
                id: 2,
                name: 'Gather & Graze',
                category: 'Catering',
                price: 3600,
                status: 'Shortlisted',
                detail: 'Working lunch & evening menu',
                initial: 'G',
            },
            {
                id: 3,
                name: 'The Supper Club',
                category: 'Catering',
                price: 4100,
                status: 'Considering',
                detail: 'Hosted dinner experience',
                initial: 'S',
            },
            {
                id: 4,
                name: 'Field Notes',
                category: 'Production',
                price: 2500,
                status: 'Shortlisted',
                detail: 'Stage, sound & technical support',
                initial: 'F',
            },
        ],
        expenses: [
            {
                name: 'Venue & accommodation',
                amount: 12000,
                paid: 6000,
                due: '01 Oct',
            },
            { name: 'Food & drink', amount: 3600, paid: 1000, due: '10 Oct' },
            {
                name: 'Production & design',
                amount: 2500,
                paid: 0,
                due: '12 Oct',
            },
            {
                name: 'Speakers & transport',
                amount: 4900,
                paid: 2000,
                due: '17 Oct',
            },
        ],
    },
];

export const money = (amount) =>
    new Intl.NumberFormat('en-GB', {
        style: 'currency',
        currency: 'GBP',
        maximumFractionDigits: 0,
    }).format(amount);
